# Generated by Django 5.2.12 on 2026-08-03 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0002_sectiontype_alter_question_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionoption",
            name="weight",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="Variant balli/og'irligi (0-10)",
            ),
        ),
    ]
