# Generated by Django 6.0.5 on 2026-06-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_user_alter_userdevice_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="message",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="title",
        ),
        migrations.AddField(
            model_name="notification",
            name="message_ru",
            field=models.TextField(
                blank=True, null=True, verbose_name="Xabar matni (Rus)"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="message_uz_cyrl",
            field=models.TextField(
                blank=True, null=True, verbose_name="Xabar matni (Krill)"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="message_uz_latn",
            field=models.TextField(
                blank=True, null=True, verbose_name="Xabar matni (Lotin)"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="title_ru",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Sarlavha (Rus)"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="title_uz_cyrl",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Sarlavha (Krill)"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="title_uz_latn",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Sarlavha (Lotin)"
            ),
        ),
    ]
