# Generated by Django 5.2.12 on 2026-09-15 09:25

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("new_match", "Yangi moslik"),
                    ("new_message", "Yangi xabar"),
                    ("profile_viewed", "Profil ko'rildi"),
                    ("system", "Tizim xabari"),
                ],
                default="system",
                max_length=20,
                verbose_name="Turi",
            ),
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "new_match",
                    models.BooleanField(default=True, verbose_name="Yangi moslik"),
                ),
                (
                    "new_message",
                    models.BooleanField(default=True, verbose_name="Yangi xabar"),
                ),
                (
                    "profile_viewed",
                    models.BooleanField(default=True, verbose_name="Profil ko'rildi"),
                ),
                (
                    "system_messages",
                    models.BooleanField(default=True, verbose_name="Tizim xabarlari"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bildirishnoma sozlamasi",
                "verbose_name_plural": "Bildirishnoma sozlamalari",
            },
        ),
    ]
