# Generated by Django 6.0.8 on 2026-08-12 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_remove_notification_message_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="message_ru",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="message_uz_cyrl",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="message_uz_latn",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="title_uz_cyrl",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="title_uz_latn",
        ),
        migrations.AddField(
            model_name="notification",
            name="message",
            field=models.TextField(default="", verbose_name="Xabar matni"),
        ),
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(default="", max_length=255, verbose_name="Sarlavha"),
        ),
        migrations.AlterField(
            model_name="userdevice",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notification_devices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
