# Generated by Django 6.0.8 on 2026-08-12 14:17

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MatchRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("forwarded_to_representative", "Vakilga yo'naltirildi"),
                            ("accepted", "Qabul qilindi"),
                            ("rejected", "Rad etildi"),
                        ],
                        default="pending",
                        max_length=35,
                        verbose_name="Holati",
                    ),
                ),
                (
                    "visibility_scope",
                    models.CharField(
                        choices=[
                            ("only_this_user", "Faqat shu odamga ochish"),
                            ("forward_to_representative", "Vakilim hal qilsin"),
                        ],
                        default="only_this_user",
                        max_length=30,
                        verbose_name="Kimga ochiladi",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, null=True, verbose_name="Izoh / O'zi haqida xabar"
                    ),
                ),
            ],
            options={
                "verbose_name": "Moslik so'rovi",
                "verbose_name_plural": "Moslik so'rovlari",
                "db_table": "match_requests",
            },
        ),
    ]
