# Generated by Django 6.0.8 on 2026-08-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match_requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchrequest",
            name="note",
            field=models.TextField(
                blank=True, null=True, verbose_name="Izoh / O'zi haqida xabar"
            ),
        ),
        migrations.AddField(
            model_name="matchrequest",
            name="visibility_scope",
            field=models.CharField(
                choices=[
                    ("only_this_user", "Faqat shu odamga ochish"),
                    ("forward_to_representative", "Vakilim hal qilsin"),
                ],
                default="only_this_user",
                max_length=30,
                verbose_name="Kimga ochiladi",
            ),
        ),
        migrations.AlterField(
            model_name="matchrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Kutilmoqda"),
                    ("forwarded_to_representative", "Vakilga yo'naltirildi"),
                    ("accepted", "Qabul qilindi"),
                    ("rejected", "Rad etildi"),
                ],
                default="pending",
                max_length=35,
                verbose_name="Holati",
            ),
        ),
    ]
