# Generated by Django 6.0.8 on 2026-08-12 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("match_requests", "0001_initial"),
        ("profiles", "0001_initial"),
        ("questionnaire", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchrequest",
            name="from_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_match_requests",
                to="profiles.profile",
                verbose_name="Yuboruvchi profil",
            ),
        ),
        migrations.AddField(
            model_name="matchrequest",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="match_requests",
                to="questionnaire.question",
                verbose_name="Savol",
            ),
        ),
        migrations.AddField(
            model_name="matchrequest",
            name="to_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_match_requests",
                to="profiles.profile",
                verbose_name="Qabul qiluvchi profil",
            ),
        ),
    ]
