# Generated by Django 5.2.12 on 2026-09-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("match_requests", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matchrequest",
            name="note",
        ),
        migrations.RemoveField(
            model_name="matchrequest",
            name="visibility_scope",
        ),
        migrations.AlterField(
            model_name="matchrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Kutilmoqda"),
                    ("accepted", "Qabul qilindi"),
                    ("rejected", "Rad etildi"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Holati",
            ),
        ),
    ]
