# Generated by Django 6.0.8 on 2026-08-12 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chats", "0001_initial"),
        ("match_requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="match_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_rooms",
                to="match_requests.matchrequest",
                verbose_name="Moslik so'rovi",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="chat_room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chats.chatroom",
                verbose_name="Chat xonasi",
            ),
        ),
    ]
