# Generated by Django 5.2.12 on 2026-09-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="chat_attachments/",
                verbose_name="Biriktirilgan fayl",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(blank=True, default="", verbose_name="Xabar matni"),
        ),
    ]
