# Generated by Django 5.2.12 on 2026-09-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0004_message_attachment_alter_message_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="chats.message",
                verbose_name="Javob berilgan xabar",
            ),
        ),
    ]
