# Generated by Django 5.2.12 on 2026-09-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0005_message_reply_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(
                blank=True, default="", max_length=256, verbose_name="Xabar matni"
            ),
        ),
    ]
