# Generated by Django 5.2.12 on 2026-09-03 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'verbose_name': 'Shikoyat', 'verbose_name_plural': 'Shikoyatlar'},
        ),
    ]
