# Generated by Django 5.2.12 on 2026-09-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("complaints", "0002_alter_complaint_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="enforcement_action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("warn", "Ogohlantirish yuborish"),
                    ("block", "Profilni bloklash"),
                ],
                max_length=20,
                null=True,
                verbose_name="Ko'rilgan chora",
            ),
        ),
    ]
