# Generated by Django 6.0.8 on 2026-08-12 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
        ("references", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Foydalanuvchi",
            ),
        ),
        migrations.AddField(
            model_name="profilephoto",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="profiles.profile",
                verbose_name="Profil",
            ),
        ),
        migrations.AddField(
            model_name="representativeinfo",
            name="kinship",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="representatives",
                to="references.kinship",
                verbose_name="Qarindoshlik holati",
            ),
        ),
        migrations.AddField(
            model_name="representativeinfo",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="representative_info",
                to="profiles.profile",
                verbose_name="Vakil profili",
            ),
        ),
        migrations.AddField(
            model_name="representativeinfo",
            name="target_candidate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="represented_by_infos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Biriktirilgan nomzod (User)",
            ),
        ),
    ]
