# Generated by Django 5.2.12 on 2026-09-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_representativeinfo_profile_fk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="birth_year",
        ),
        migrations.AddField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Tug'ilgan sanasi"
            ),
        ),
    ]
