# Generated by Django 5.2.12 on 2026-07-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_profile_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="role",
        ),
        migrations.AddField(
            model_name="profile",
            name="candidate_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("groom", "Kuyov"),
                    ("bride", "Kelin"),
                    ("representative", "Vakil"),
                ],
                max_length=20,
                null=True,
                verbose_name="Nomzod turi (Kuyov/Kelin/Vakil)",
            ),
        ),
        migrations.AlterField(
            model_name="representativeinfo",
            name="kinship",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Qarindoshlik holati",
            ),
        ),
    ]
