# Generated by Django 5.2.12 on 2026-08-03 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_remove_profile_role_profile_candidate_type_and_more"),
        ("references", "__first__"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="children_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Farzandlar soni"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="education_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profiles",
                to="references.educationlevel",
                verbose_name="Ta'lim darajasi",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="expectations",
            field=models.TextField(
                blank=True, null=True, verbose_name="Kutilmalar / Talablar"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="has_children",
            field=models.BooleanField(
                default=False, verbose_name="Farzandlari bor-yo'qligi"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="nationality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profiles",
                to="references.nationality",
                verbose_name="Millati",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="profession",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profiles",
                to="references.profession",
                verbose_name="Kasbi",
            ),
        ),
    ]
