# Generated by Django 5.2.12 on 2026-08-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_profile_children_count_profile_education_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="children_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Farzandlar soni"
            ),
        ),
    ]
