# Generated by Django 5.2.12 on 2026-08-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_alter_profile_health_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("never_married", "Birinchi marta turmush qurmoqchi"),
                    ("divorced", "Ajrashgan"),
                ],
                max_length=20,
                null=True,
                verbose_name="Oilaviy holati",
            ),
        ),
    ]
