# Generated by Django 5.2.12 on 2026-08-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0010_alter_profile_candidate_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="candidate_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("groom", "Kuyov"),
                    ("bride", "Kelin"),
                    ("representative", "Vakil"),
                ],
                max_length=20,
                null=True,
                verbose_name="Nomzod turi (Kuyov/Kelin/Vakil)",
            ),
        ),
        migrations.AlterField(
            model_name="representativeinfo",
            name="candidate_role",
            field=models.CharField(
                choices=[("groom", "Kuyov"), ("bride", "Kelin")],
                max_length=20,
                verbose_name="Vakillik qilayotgan nomzod turi (Kuyov/Kelin)",
            ),
        ),
    ]
