# Generated by Django 5.2.12 on 2026-08-03 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0010_alter_profile_marital_status"),
        ("references", "0004_maritalstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="marital_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profiles",
                to="references.maritalstatus",
                verbose_name="Oilaviy holati",
            ),
        ),
    ]
