# Generated by Django 5.2.12 on 2026-08-06 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0013_profile_location"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "permissions": [
                    ("change_me_profile", "O'z profilini tahrirlash"),
                    ("delete_me_profile", "O'z profilini o'chirish"),
                ],
                "verbose_name": "Profil Anketa",
                "verbose_name_plural": "Profil Anketalari",
            },
        ),
    ]
