# Generated by Django 5.2.12 on 2026-08-08

from django.db import migrations, models


def normalize_active_photos(apps, schema_editor):
    ProfilePhoto = apps.get_model("profiles", "ProfilePhoto")
    profile_ids = (
        ProfilePhoto.objects.filter(is_active=True)
        .values_list("profile_id", flat=True)
        .distinct()
    )
    for profile_id in profile_ids:
        photos = list(
            ProfilePhoto.objects.filter(profile_id=profile_id, is_active=True).order_by(
                "order", "created_at", "id"
            )
        )
        for index, photo in enumerate(photos, start=1):
            ProfilePhoto.objects.filter(pk=photo.pk).update(order=index, is_main=False)
        main_photo = next((photo for photo in photos if photo.is_main), None)
        if main_photo:
            ProfilePhoto.objects.filter(pk=main_photo.pk).update(is_main=True)


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0014_alter_profile_options"),
    ]

    operations = [
        migrations.RunPython(normalize_active_photos, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="profile",
            name="weight",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Vazni (kg)"
            ),
        ),
        migrations.AddConstraint(
            model_name="profilephoto",
            constraint=models.UniqueConstraint(
                condition=models.Q(is_active=True),
                fields=("profile", "order"),
                name="unique_active_profile_photo_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="profilephoto",
            constraint=models.UniqueConstraint(
                condition=models.Q(is_active=True, is_main=True),
                fields=("profile",),
                name="unique_active_main_profile_photo",
            ),
        ),
    ]
