# Generated by Django 5.2.12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0014_alter_profile_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="weight",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Vazni (kg)"
            ),
        ),
    ]
