# Generated by Django 5.2.12 on 2026-08-11 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0015_alter_profile_weight"),
        ("references", "0003_kinship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="representativeinfo",
            name="kinship",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="representatives",
                to="references.kinship",
                verbose_name="Qarindoshlik holati",
            ),
        ),
    ]
