# Generated by Django 5.2.12 on 2026-08-11 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0015_alter_profile_weight"),
        ("references", "0003_kinship"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "permissions": [
                    ("change_me_profile", "O'z profilini tahrirlash"),
                    ("delete_me_profile", "O'z profilini o'chirish"),
                ],
                "verbose_name": "Profil Anketa",
                "verbose_name_plural": "Profil Anketalari",
            },
        ),
        migrations.AlterField(
            model_name="representativeinfo",
            name="kinship",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="representatives",
                to="references.kinship",
                verbose_name="Qarindoshlik holati",
            ),
        ),
    ]
