# Generated by Django 5.2.12 on 2026-08-11 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0014_alter_profile_options"),
        ("profiles", "0016_alter_representativeinfo_kinship"),
    ]

    operations = []
