# Generated by Django 6.0.8 on 2026-08-12 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0017_merge_migrations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "verbose_name": "Profil Anketa",
                "verbose_name_plural": "Profil Anketalari",
            },
        ),
        migrations.AddField(
            model_name="representativeinfo",
            name="candidate_contact",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Nomzodning telefon raqami yoki email manzili",
            ),
        ),
        migrations.AddField(
            model_name="representativeinfo",
            name="is_approved",
            field=models.BooleanField(
                default=False, verbose_name="Nomzod tomonidan rozilik berilganmi?"
            ),
        ),
        migrations.AddField(
            model_name="representativeinfo",
            name="target_candidate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="represented_by_infos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Biriktirilgan nomzod (User)",
            ),
        ),
    ]
