# Generated by Django 5.2.12 on 2026-08-03 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0010_alter_profile_marital_status"),
        ("references", "0002_healthstatus_maritalstatus"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MaritalStatus",
        ),
    ]
