# Generated by Django 5.2.12 on 2026-09-02 12:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profiles", "0005_rename_birth_year_to_birth_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("accepted", "Qabul qilindi"),
                            ("rejected", "Rad etildi"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Holati",
                    ),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="Izoh")),
                (
                    "from_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_photo_requests",
                        to="profiles.profile",
                        verbose_name="Yuboruvchi profil",
                    ),
                ),
                (
                    "to_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_photo_requests",
                        to="profiles.profile",
                        verbose_name="Qabul qiluvchi profil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rasm ko'rish so'rovi",
                "verbose_name_plural": "Rasm ko'rish so'rovlari",
                "db_table": "photo_requests",
            },
        ),
    ]
