# Generated by Django 5.2.12 on 2026-09-08 10:19

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Psychologist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Ismi")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Familiyasi"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Telefon raqami noto'g'ri formatda kiritildi. Kutilgan format: '+998901234567'. Uzunligi aynan 13 ta belgi bo'lishi shart.",
                                regex="^\\+998\\d{9}$",
                            )
                        ],
                        verbose_name="Telefon raqam",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(max_length=255, verbose_name="Mutaxassislik"),
                ),
                (
                    "experience_years",
                    models.PositiveSmallIntegerField(verbose_name="Tajriba (yil)"),
                ),
                (
                    "price",
                    models.PositiveIntegerField(verbose_name="Sessiya narxi (so'm)"),
                ),
                (
                    "session_duration_minutes",
                    models.PositiveSmallIntegerField(
                        verbose_name="Sessiya davomiyligi (daqiqa)"
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Tavsif")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="psychologists/",
                        verbose_name="Rasm",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Qabul qilmoqda"
                    ),
                ),
            ],
            options={
                "verbose_name": "Psixolog",
                "verbose_name_plural": "Psixologlar",
                "db_table": "psychologists",
            },
        ),
    ]
