# Generated by Django 5.2.12 on 2026-09-02 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=20,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Telefon raqami noto'g'ri formatda kiritildi. Kutilgan format: '+998901234567'. Uzunligi aynan 13 ta belgi bo'lishi shart.",
                        regex="^\\+998\\d{9}$",
                    )
                ],
                verbose_name="Telefon raqam",
            ),
        ),
    ]
