# Generated by Django 5.2.12 on 2026-09-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Admin panelga kiruvchi xodim/admin uchun profil rasmi",
                null=True,
                upload_to="admin_avatars/",
                verbose_name="Rasm",
            ),
        ),
    ]
