# Generated by Django 5.2.12 on 2026-07-30 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_auth_provider"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="pin_code",
        ),
    ]
