# Generated by Django 5.2.12 on 2026-09-12 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blocked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Bloklangan vaqti"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="blocked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blocked_users_by_admin",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Bloklagan xodim",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="blocked_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="Bloklash sababi"
            ),
        ),
    ]
