# Generated by Django 5.2.12 on 2026-09-12 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_blocked_at_user_blocked_by_user_blocked_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="unblocked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Blokdan chiqarilgan vaqti"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="unblocked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unblocked_users_by_admin",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Blokdan chiqargan xodim",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="unblocked_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="Blokdan chiqarish sababi"
            ),
        ),
    ]
