import django.core.validators
import uuid
from django.db import migrations, models

FIX_ROLE_ID_TYPE_SQL = """
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_name = 'users_role' AND column_name = 'id' AND data_type != 'uuid'
    ) THEN
        ALTER TABLE "users" DROP CONSTRAINT IF EXISTS "users_role_id_fkey" CASCADE;
        ALTER TABLE "users" DROP COLUMN IF EXISTS "role_id" CASCADE;
        DROP TABLE IF EXISTS "users_role_permissions" CASCADE;
        DROP TABLE IF EXISTS "users_role" CASCADE;

        CREATE TABLE "users_role" (
            "id" uuid NOT NULL PRIMARY KEY,
            "created_at" timestamp with time zone NOT NULL,
            "updated_at" timestamp with time zone NOT NULL,
            "is_active" boolean NOT NULL,
            "name" varchar(150) NOT NULL UNIQUE
        );

        CREATE TABLE "users_role_permissions" (
            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            "role_id" uuid NOT NULL REFERENCES "users_role" ("id") DEFERRABLE INITIALLY DEFERRED,
            "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT "users_role_permissions_role_id_permission_id_uniq" UNIQUE ("role_id", "permission_id")
        );

        ALTER TABLE "users" ADD COLUMN "role_id" uuid NULL REFERENCES "users_role" ("id") DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0008_add_role_model_and_fk"),
    ]

    operations = [
        migrations.RunSQL(
            sql=FIX_ROLE_ID_TYPE_SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="role",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Yaratilgan vaqti"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Is Active"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                db_index=True,
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Telefon raqami noto'g'ri formatda kiritildi. Kutilgan format: '+9989012345678'. Uzunligi aynan 13 ta belgi bo'lishi shart.",
                        regex="^\\+998\\d{9}$",
                    )
                ],
                verbose_name="Telefon raqam",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
