# Generated by Django 5.2.12 on 2026-07-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_add_is_default_to_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_blocked",
            field=models.BooleanField(
                default=False, verbose_name="Bloklangan foydalanuvchi"
            ),
        ),
    ]
