# Generated by Django 5.2.12 on 2026-08-01 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_user_is_blocked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(
                choices=[
                    ("google", "Google"),
                    ("phone", "Phone"),
                    ("telegram", "Telegram"),
                    ("email", "Email"),
                ],
                default="phone",
                max_length=20,
                verbose_name="Ro'yxatdan o'tgan usuli",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=20,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Telefon raqami noto'g'ri formatda kiritildi. Kutilgan format: '+9989012345678'. Uzunligi aynan 13 ta belgi bo'lishi shart.",
                        regex="^\\+998\\d{9}$",
                    )
                ],
                verbose_name="Telefon raqam",
            ),
        ),
    ]
