# Generated by Django 5.2.12 on 2026-08-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_user_auth_provider_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                null=True,
                unique=True,
                verbose_name="Telegram ID",
            ),
        ),
    ]
