# Generated by Django 5.2.12 on 2026-08-06 06:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_blockedface"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Qurilma ID"
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Qurilma nomi",
                    ),
                ),
                (
                    "device_os",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Qurilma operatsion tizimi",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP manzil"
                    ),
                ),
                (
                    "last_active",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Oxirgi faollik vaqti"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foydalanuvchi qurilmasi",
                "verbose_name_plural": "Foydalanuvchi qurilmalari",
                "db_table": "user_devices",
                "unique_together": {("user", "device_id")},
            },
        ),
    ]
