# Generated by Django 6.0.8 on 2026-08-12 07:55

import apps.accounts.telegram_bot.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramAuthSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Sessiya ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("authenticated", "Tasdiqlangan"),
                            ("expired", "Muddati o'tgan"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Holat",
                    ),
                ),
                (
                    "access_token",
                    models.TextField(
                        blank=True, null=True, verbose_name="Access Token"
                    ),
                ),
                (
                    "refresh_token",
                    models.TextField(
                        blank=True, null=True, verbose_name="Refresh Token"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=apps.accounts.telegram_bot.models.default_expires_at,
                        verbose_name="Amal qilish muddati",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram Auth Sessiyasi",
                "verbose_name_plural": "Telegram Auth Sessiyalari",
                "db_table": "telegram_auth_sessions",
                "ordering": ["-created_at"],
            },
        ),
    ]
