# Generated by Django 5.2.12 on 2026-08-01 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0002_telegramauthsession"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LoginCode",
        ),
    ]
