# Generated by Django 5.2.12 on 2026-07-29 14:17

import apps.telegram_bot.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoginCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Telefon raqam"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=apps.telegram_bot.models.generate_code,
                        max_length=6,
                        verbose_name="Tasdiqlash kodi",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="Ishlatilgan"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=apps.telegram_bot.models.default_expires_at,
                        verbose_name="Amal qilish muddati",
                    ),
                ),
            ],
            options={
                "verbose_name": "Login kodi",
                "verbose_name_plural": "Login kodlari",
                "db_table": "telegram_login_codes",
                "ordering": ["-created_at"],
            },
        ),
    ]
