name: Deploy Raqamli Sovchi Backend

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          envs: GITHUB_TOKEN
          script: |
            set -e
            cd /var/www/backend/raqamli-sovchi-backend
            
            echo "1. Kodni yangilash (Production)"
            git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/raqamli-nazorat/raqamli-sovchi-backend.git
            git fetch origin production
            git reset --hard origin/production
            
            echo "2. Kutubxonalarni yangilash"
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            
            echo "3. Migratsiya va Statika"
            python manage.py migrate --noinput
            python manage.py load_locations
            python manage.py load_questions
            python manage.py collectstatic --noinput
            
            
            echo "4. Servislarni qayta yoqish"
            sudo systemctl restart raqamli-sovchi-backend-web
            sudo systemctl restart raqamli-sovchi-backend-bot

            sudo systemctl reload nginx
            
            echo "Muvaffaqiyatli yakunlandi!"